"""Add image field to Producto and ProductoVariante models

Revision ID: 77c24fef5ef8
Revises: bf2fc42016b4
Create Date: 2026-04-13 17:17:17.584804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c24fef5ef8'
down_revision = 'bf2fc42016b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ProductoVariantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Imagen', sa.String(length=255), nullable=True))

    with op.batch_alter_table('Productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Imagen', sa.String(length=255), nullable=True))
        batch_op.drop_constraint(batch_op.f('FK__Productos__IdCol__2739D489'), type_='foreignkey')
        batch_op.drop_column('IdColor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IdColor', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('FK__Productos__IdCol__2739D489'), 'Colores', ['IdColor'], ['IdColor'])
        batch_op.drop_column('Imagen')

    with op.batch_alter_table('ProductoVariantes', schema=None) as batch_op:
        batch_op.drop_column('Imagen')

    # ### end Alembic commands ###
