"""Agregar columna activo a tabla Inventario

Revision ID: 9e8e018e80da
Revises: 77c24fef5ef8
Create Date: 2026-04-14 23:50:55.537391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8e018e80da'
down_revision = '77c24fef5ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Activo', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Inventario', schema=None) as batch_op:
        batch_op.drop_column('Activo')

    # ### end Alembic commands ###
