"""Add foreign key id_color to Producto

Revision ID: bf2fc42016b4
Revises: c3632b6fd1dc
Create Date: 2026-04-12 16:50:39.257683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf2fc42016b4'
down_revision = 'c3632b6fd1dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IdColor', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'Colores', ['IdColor'], ['IdColor'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('IdColor')

    # ### end Alembic commands ###
