"""add comentario field to estados_pedido

Revision ID: c3632b6fd1dc
Revises: 0314a2ec02ba
Create Date: 2026-04-03 09:39:45.862762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3632b6fd1dc'
down_revision = '0314a2ec02ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('EstadosPedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Comentario', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('EstadosPedido', schema=None) as batch_op:
        batch_op.drop_column('Comentario')

    # ### end Alembic commands ###
