"""Add direccion telefono notas to Pedidos

Revision ID: e1fcde78019a
Revises: 9e8e018e80da
Create Date: 2026-04-16 00:34:02.692004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1fcde78019a'
down_revision = '9e8e018e80da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Direccion', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('Telefono', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('Notas', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pedidos', schema=None) as batch_op:
        batch_op.drop_column('Notas')
        batch_op.drop_column('Telefono')
        batch_op.drop_column('Direccion')

    # ### end Alembic commands ###
